### ISSUE TITLE
Ensure routing info doesn't use pre-allocated resources

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/PACMAN#113]
On SpiNNaker, some of the keys are reserved for system use.  These should be pre-allocated to avoid them being assigned to a vertex.

Note that this will rarely be an issue for smaller networks as the keys reserved are at the top end of the key space, but the allocations tend to be made at the bottom end upwards.  This should be fixed eventually though to avoid issues in the future.

**Comment by Christian-B** [comment]
Considering the size of models we are running without hitting this in 7 years closing.

Reopen with an example if it is needed.
