### ISSUE TITLE
Add "Smart Token" support

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/PACMAN#133]
The current executor does not allow for a number of algorithms unknown to algorithm A to be executed before it (other than through the explicit ordering of the algorithms provided to the executor, which has been deemed unacceptable for this purpose).  An example of this is in data loading - there may be any number of algorithms that are involved in the loading of data, with more being added depending on the front-end application, but the binary loader should not (and cannot) know about all these algorithms.  

To avoid a need to rewrite the binary loader for each front-end, a "Smart" of "Composite" token should be supported.  This token would ensure that all required algorithms that produce the token as output must be run before any algorithm that takes the token as input.

This might operate in one of the following ways:
- The exact requirement is built into PACMAN that all required algorithms that take a smart token as input and output the same smart token must be run before any algorithm that takes that smart token as an input,
- Additional (optional) metadata is added to each algorithm that indicates the parts of a specified composite token that it fulfils.  Only when all parts of a composite token have been run will an algorithm that requires the token be executed.  The parts of the composite token can then be dynamically determined by the algorithms in the chain that generate the token.  In the example of data loading, each algorithm that can load data will declare explicitly that it generates part of a "DataLoading" token e.g. DataLoading:DSG indicates an algorithm that generates the DSG part of a DataLoading token.  If this algorithm is optional, it will be run if no other algorithm can generate the DSG part of the DataLoading token.  A future algorithm only requires that DataLoading token is produced; this will only be true when all parts of the composite token are fulfilled.

**Comment by rowleya** [comment]
Fixed in SpiNNakerManchester/PACMAN#133

**Comment by alan-stokes** [comment]
merged into master. closing
