### ISSUE TITLE
Bring File convertor to Alan's Standards.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#183]
From https://github.com/SpiNNakerManchester/PACMAN/pull/182

spinnMachine (machine.py).MAX_CORES_IN_MACHINE

no point duplicating.

time to fix the other convertors.

**Comment by Christian-B** [comment]
@alan-stokes wants calls to have docs.

**Comment by Christian-B** [comment]
@alan-stokes 
"f! f! 1 letter variable! seriously!"

So these need fixing in other convertors.

**Comment by Christian-B** [comment]
@alan-stokes code! @alan-stokes Stanard's @alan-stokes Issue!

**Comment by alan-stokes** [comment]
so does that mean I have to fix everything? if so, what do we pay ya for? apart from to wind me up, which might be a valid job description i guess in its own right.

**Comment by Christian-B** [comment]
Code moved and replacement good as good as it is going to get.
