### ISSUE TITLE
OneToOnePlacer might be overzealous

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/PACMAN#190]
I have seen a circumstance under which the OneToOnePlacer might be trying a bit too hard.  The issue seemed to come up with a 512 neuron retina population connected to a single population of 256 neurons, where the connected population then has 16 atoms per core as a restriction.  This attempted to put all of the 16 cores on to 0, 0 by force.  This has two issues:
 - Nothing was constraining the population to 0, 0.  This was tested by putting a constraint of 0, 1 on the population, which then worked.
 - If OneToOnePlacer fails to place connected vertices together, it shouldn't fail but instead just place as normal.

This sounds to me like the OneToOnePlacer expecting a certain exception to occur when a grouped placement fails, but instead receiving a different one.

**Comment by alan-stokes** [comment]
this i think is due to this line:

if len(vertex_list) > machine.maximum_user_cores_on_chip:

i have a fix, on the nengo side (not sure if it came into master yet) where you can ask for max cores when taking into account pre allocoated resoruces. 

i bet thats the issue here. if going to 0, 1 works, as thats got one less pre allocated resoruce if speed up is turned on.

**Comment by alan-stokes** [comment]
resource tracker. get_maximum_cores_available_on_a_chip()

**Comment by alan-stokes** [comment]
its already in master. that would ensure its going on a chip that would hold it. If it goes above a chip capability, it should be fine, as its meant to allocate individually at that point. 

            if len(vertex_list) > machine.maximum_user_cores_on_chip:
                for vertex in progress.over(vertex_list, False):
                    self._allocate_individual(
                        vertex, placements, resource_tracker,
                        same_chip_vertex_groups, all_vertices_placed)
                continue

**Comment by alan-stokes** [comment]
https://github.com/SpiNNakerManchester/PACMAN/pull/191
