### ISSUE TITLE
injector_decorator not clearing

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#205]
If you run script that inject items and then other script the injected items stay behind.

testfix is to add to
globals_variables.unset_simulator()
injection_decorator._instances = list()

or should this go into 
 AbstractSpinnakerBase.__init__

or low and behold actually fix the hacking injector ?????

**Comment by andrewgait** [comment]
I think this was dealt with by the commits above, so closing this.
