### ISSUE TITLE
do partitioner costs on size on slice

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#207]
Partitioners are application vertex and application edge based.

So they only consider the size of the slice

So why not calc once for each size and cache?

**Comment by Christian-B** [comment]
SpikeSourcePoisson With different rates for different neurons may need to be done slice based.

need to check if selective recording takes slice into consideration. It should.

**Comment by alan-stokes** [comment]
coz different neurons will have different size requirements. different synaptic block sizes etc.

**Comment by alan-stokes** [comment]
and coz we try to keep to 1 consistent API. but ignore this for the time being. when i get to merging roberts spinnear, its all going to change.

**Comment by Christian-B** [comment]
Not possible as the sdram requirements change on edges.

As cost per slice may not be the best way forward anyway.
