### ISSUE TITLE
Report algorithm misnamed

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/PACMAN#227]
https://github.com/SpiNNakerManchester/PACMAN/blob/58a4afd0112dd3bb3f1192fed9419a58adb5bc8d/pacman/operations/algorithm_reports/reports_metadata.xml#L170

We should change `SdramUsageReportPperChip` to `SdramUsageReportPerChip` because it is a name that is visible to users (in timing logging). Requires a trivial matching change in FEC.

**Comment by andrewgait** [comment]
This was fixed in recent merges, so closing.
