### ISSUE TITLE
ZonedRoutingInfoAllocator will not work if not all machineVertex needs keys

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#249]
The ZonedRoutingInfoAllocator depends on
 graph_mapper.get_machine_vertex_index

This will be a problem if there are more machine Vertex than those that need keys.

needs to be reevaluated.

**Comment by alan-stokes** [comment]
this sounde even worse given the gm death thats incoming.....

**Comment by Christian-B** [comment]
Will reconsidered when the graph mapper monster is gone.

**Comment by Christian-B** [comment]
Solved with machine_graph.multicast_partitions
