### ISSUE TITLE
Router constraints are useless

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/PACMAN#250]
We have the module `pacman.model.constraints.router_constraints` which only defines a single abstract class, `AbstractRouterConstraint`, that nothing checks for or subclasses as a concrete class. Or even as another abstract class. It's use-less, and so is useless.

Can we delete the module? Defining a constraint using it will just result in that constraint being ignored; our routers don't roll that way.

**Comment by Christian-B** [comment]
Done in https://github.com/SpiNNakerManchester/PACMAN/pull/247
