### ISSUE TITLE
placer can not do all chore constraints:

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#268]
The placer sorts vertexes by constraints then groups them and places by group.

In raw weird cases this can cause an error;

Script:
import spynnaker8 as sim
from pacman.model.constraints.placer_constraints import ChipAndCoreConstraint

sim.setup(timestep=1.0, n_boards_required=1)
machine = sim.get_machine()
input1 = sim.Population(
    1, sim.SpikeSourceArray(spike_times=[0]), label="input1")
input2 = sim.Population(
    1, sim.SpikeSourceArray(spike_times=[0]), label="input2")
pop_1 = sim.Population(5, sim.IF_curr_exp(), label="pop_1")
pop_2 = sim.Population(5, sim.IF_curr_exp(), label="pop_2")
sim.Projection(input1, pop_1, sim.AllToAllConnector(),
               synapse_type=sim.StaticSynapse(weight=5, delay=18))
sim.Projection(input2, pop_2, sim.AllToAllConnector(),
               synapse_type=sim.StaticSynapse(weight=5, delay=18))

input1.set_constraint(
    ChipAndCoreConstraint(0, 0, 1))
input2.set_constraint(
    ChipAndCoreConstraint(0, 0, 3))
pop_1.set_constraint(
     ChipAndCoreConstraint(1, 1, 1))
pop_2.set_constraint(
    ChipAndCoreConstraint(0, 0, 2))

sim.run(500)
sim.end()

Error:
No resources available to allocate the given resources within the given constraints:

The issue is that when we place input on 0,0,1 we place the delay on 0,0,2
the error message is confusing

**Comment by Christian-B** [comment]
Improved the error message with https://github.com/SpiNNakerManchester/PACMAN/issues/268

**Comment by Christian-B** [comment]
Closing will not fix for the following reasons.

These constraint are only really useful for testing and test writes should know how to avoid these issues.

In a later stage of the self partitioning work it would be better for delay vertexes to ONLY be added at the machine level and never at the graph level.

**Comment by alan-stokes** [comment]
"In a later stage of the self partitioning work it would be better for delay vertexes to ONLY be added at the machine level and never at the graph level."

mmmmm...... that would also allow you to basically remove the filterer fully..... never throught of that. good catch
