### ISSUE TITLE
Target based Routing key allocator

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#277]
As we are still getting compression problems despite having a only about 20 to 30 unique targets work could be done to see if target based key allocation is possible and helps.

The idea is to sacrifice the continuous/ near continuous key range of keys for the machine vertexes in an App vertexes and instead have the target be the main decider.

Allocate each machine vertex separately

Reserve the same number of bites for the neurons on every vertex. Typically 8
(Sorry @alan-stokes  the Retina CAN NOT be supported this way!)

Then group the machineVertex by target and allocate keys so that vertexes with the same target share the same power of 2 block. And no other vertexes are in that power of two block.

**Comment by Christian-B** [comment]
Step 1 is do some reporting so see if there are in fact vertexes that share targets.

Step 2 is see if the MachineGraph json is enough to generate keys

Step 3 is to write algorithm

Step 4 test with big 500 plus board machine graph json @rowleya can provide

**Comment by alan-stokes** [comment]
ignoring the criticle issue that if this became a default key allocator, then you'd lose support to external devices. 

what do you mean by "target be the main decider." you going to start allocating keys on a target basis? aka NOT MC!???????

**Comment by Christian-B** [comment]
Work done elsewhere and being done in https://github.com/SpiNNakerManchester/PACMAN/tree/reduce_overhead make this idea irrelevant
