### ISSUE TITLE
Validation failing due to fields not being of 'int' type

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/PACMAN#320]
Validator complains because these fields end up being int64. I'm computing population size stuff with Numpy and using their 'int' type. The validation is fixed by parsing these two fields as native Python int.
https://github.com/SpiNNakerManchester/PACMAN/blob/387fe3fa28784c8d871dac6872283aa6aaa16218/pacman/utilities/json_utils.py#L191-L192

**Comment by Christian-B** [comment]
The route cause is that the json schema validator can not handle int64
https://github.com/adobe/xdm/issues/427

**Comment by rowleya** [comment]
It would be reasonable to wrap the two calls mentioned with an "int"; I guess that numpy uses int64 by default (the fun of types in an untyped language) but if the values were truly not int32, they would be too big anyway!

**Comment by Christian-B** [comment]
Converting the values to int is possible see https://github.com/SpiNNakerManchester/PACMAN/pull/321

The worrying thing is now the int64 value got into the system.

The init method of PyNN population convert size to int so I would like to know how the "I'm computing population size stuff with Numpy" stuff is getting in.

**Comment by rowleya** [comment]
Fix merged into master

**Comment by Christian-B** [comment]
While the above fix hides the issue I still worry how the int64 got into the system.

**Comment by chanokin** [comment]
aaah shit, yes, I forgot to mention made a converter thingy to make it compatible with Numpy types but it should spit out Python data types. I'll investigate further

**Comment by Christian-B** [comment]
I don’t mind if you use numpy type. You as a user or model developer should be allowed to. We want to know where you are doing it so we can make sure the tools do the conversion in the right places so developers don’t need to worry about types

**Comment by chanokin** [comment]
OK, I have traced this as much as I can. The number comes from mixing Numpy and Python types. When passing in the Population size, this remains a Numpy type (`int32` in my case) stored as `n_atoms` in [abstract_population_vertex.py](https://github.com/SpiNNakerManchester/sPyNNaker/blob/c3465af2c19b437212465d8c0e1427ed068787d7/spynnaker/pyNN/models/neuron/abstract_population_vertex.py#L138) ). 

This later causes the [partitioner calculations for vertex slices](https://github.com/SpiNNakerManchester/PACMAN/blob/11d1b920c2a85475ec30d339b0f1e56befd6a786/pacman/operations/partition_algorithms/partition_and_place_partitioner.py#L199) to mix Python + Numpy, this again propagates the number as a Numpy type (this time as an `int64`). 

After a bunch of jumps here and there, it lands to `dtcm` and `cpu_cycles` computations and, you guessed it, they remain Numpy types. Then this goes to the JSON packing which complains about the data type not being a native Python Integer. 

This could be 'fixed' in many places, e.g. cast `n_neurons` to `int` in abstract_population_vertex.py or force types in Slices to be `int`.

**Comment by Christian-B** [comment]
Thank you that is extremely useful.
I will fix it as much as possible that what goes into n_atoms is converted to python int

**Comment by alan-stokes** [comment]
im 100% ive already made slices only accept ints in slef partitioning. so maybe this is fixed once that stuff goes in
