### ISSUE TITLE
Incorrect formatting in splitter message

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/PACMAN#335]
This line: https://github.com/SpiNNakerManchester/PACMAN/blob/2c604f0a1730e666d47b0bf048747f176d7fb697/pacman/model/partitioner_splitters/splitter_one_app_one_machine.py#L42 appears wrong (and possibly in other splitters too) since STR_MESSAGE requires two arguments and only one is given.  I'm not sure whether STR_MESSAGE is wrong or that something else should be being passed in here instead.

**Comment by alan-stokes** [comment]
needs self._splitter_name
