### ISSUE TITLE
Sphinx type trickery?

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/PACMAN#338]
Should we use [`collections.abc.Iterator`](https://cpython-test-docs.readthedocs.io/en/latest/library/collections.abc.html#collections.abc.Iterator) as the type to link to in our documentation? I'm talking about when doing things like this (very stupid, non-real but legal and possible situation):

```python
def foo(x):
    """
    :rtype: iterable(int)
    """
    for y in range(x):
        yield x ^ y
```

That would change the documented type to: `~collections.abc.Iterator(int)` which ought to link correctly (as `Iterator(int)`) when Sphinx processes it. (NB: might need to be Iterable instead of Iterator; I tend to mix those up.)

Note that we can't link directly to the Python concept of iterator when doing type annotation processing; that's not a type in the Python docs, it's a _concept._

**Comment by dkfellows** [comment]
`Callable` would be another thing we could do this for.

**Comment by Christian-B** [comment]
A good idea but will have to wait until we get rid of python 2.7

Reason is that collections.abc did not exist in python 2.7

**Comment by dkfellows** [comment]
All done or will be subsumed by #513
