### ISSUE TITLE
"Rigged" algorithms Keep or Nuke

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#386]
We currently still have two placer in the pacman/operations/rigged_algorithms directory

However these are
1. NOT tested
2. Dont use Rig any more
3. Dont repect RadialPlacementFromChipConstraint
Testing these with PACMAN/unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
- test_deal_with_constraint_placement_vertices_dont_have_vertex fails

There are also test which should fail with a different exception but that is not critical

--
Do we fix or Nuke?
Fix is
1. Move to pacman/operations/placer_algorithms
2. Fix _check_constraints to not just accept all the ResourceTracker can handle
3. Add tests

**Comment by rowleya** [comment]
Happy enough to nuke - maybe with a link to the code nuked in this issue?  That way if someone should come to us in the future wanting some more specific placement algorithms, we at least have reference to them (not likely hence nuke and link).
