### ISSUE TITLE
BasicRoutingInfoAllocator keep or update

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#387]
BasicRoutingInfoAllocator is currently unused and tested.

It appears to work when tested.
easiest way to test is add it to a placer test such as PACMAN/unittests/operations_tests/placer_algorithms_tests/test_spreader_placer.py

If kept I would suggesting adding checks to go pop if x, y or  n_keys is too big.

**Comment by rowleya** [comment]
I don't think routing key allocation takes long enough just now for us to need something simpler, so I advise nuke.  This is also really easy to bring back if I am wrong!
