### ISSUE TITLE
package directory 'pacman/interfaces' (in setup.py) does not exist

### ISSUE THREAD

**Issue by ericnichols** [SpiNNakerManchester/PACMAN#40]
1. running "sudo python setup.py develop" in PACMAN's directory in a terminal, I get the following output:
error: package directory 'pacman/interfaces' does not exist

2. line 13 of setup.py contains: 'pacman.interfaces',
(https://github.com/SpiNNakerManchester/PACMAN/blob/master/setup.py#L13) 

3. the pacman directory does not contain a file or directory named interfaces:
(https://github.com/SpiNNakerManchester/PACMAN/tree/master/pacman)

I think line 13 of setup.py needs to be either removed or changed to the current location of "interfaces".

Eric

P.S. 
Line 52 in the same setup.py file is looking for SpiNNMachine version 2016.001. 
(https://github.com/SpiNNakerManchester/PACMAN/blob/master/setup.py#L52) 
However, the latest version in GitHub of SpiNNMachine is 2015.004.01.
(https://github.com/SpiNNakerManchester/SpiNNMachine/blob/master/setup.py#L8)
But, I'm sure SpiNNMachine will soon be changed to 2016.001 to fix this issue.

**Comment by alan-stokes** [comment]
Hi eric, 

the setup.py's have not been updated with the shed load of brnahces that have been merged in recnetly. Therefore if your trying to install the tools by github, your going to hit this issue till the enxt release is done (at which point all these thigns clean up).,

If you need to work with master devleopment, I recommend using a IDE which ahs a virutal enviroment control that means you dont need to install the tools. I recommend PyCharm for this, whereas i know Eclipse can do the same thing. 

regards
alan

**Comment by ericnichols** [comment]
Hi Alan,

Thanks a lot. 
PyCharm works like a charm :+1: 

Eric
