### ISSUE TITLE
Consider renaming RoutingInfo 

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#441]
There are classes with a single RoutingInfo 
was PartitionRoutingInfo
Reduce Overhead VertexRoutingInfo, MachineVertexRoutingInfo, AppVertexRoutingInfo

Maybe consider renaming the RoutingInfo object.

But best left until after the reduce_overhead global_data merges

**Comment by Christian-B** [comment]
In RO there is a method
RoutingInfo.add_routing_info whic does not add a RoutingInfo

**Comment by Christian-B** [comment]
We could rename it to RoutingInfos but is it worth a change?

**Comment by rowleya** [comment]
Probably not; one of the complications of information being both plural and singular!
