### ISSUE TITLE
Avoid casting in splitter code

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/PACMAN#531]
Currently some splitters need the type of the vertex to be something specific.  This has led to the use of isinstance in one method and cast in another.  This suggests a refactor of the splitter API, so that the splitter has an abstract get_governed_app_vertex and set_governed_app_vertex, so it can keep its own type of vertex internally.

**Comment by Christian-B** [comment]
The methods already exist!

https://github.com/SpiNNakerManchester/PACMAN/blob/d49ffca3e0f9e6bc5298be9335b5bc729c693b8d/pacman/model/partitioner_splitters/abstract_splitter_common.py#L53

https://github.com/SpiNNakerManchester/PACMAN/blob/d49ffca3e0f9e6bc5298be9335b5bc729c693b8d/pacman/model/partitioner_splitters/abstract_splitter_common.py#L66

**Comment by Christian-B** [comment]
where it gets messy is in case like the 

SplitterFixedLegacy

Where the type needed is sometimes a LegacyPartitionerAPI which does not inherit from ApplicationVertext so the governed_app_vertex can not be changed to return a LegacyPartitionerAPI

**Comment by Christian-B** [comment]
Any fix would include either requiring more specific Spliiters for the Various Vertex (including user ones) or dropping slots to do diamond inheritance.

IsInstance is a safetly check while casts is a very cheap do nothing method for mypy.
They are the cost of doing typing without duplicating a lot of code.
