### ISSUE TITLE
ApplicationPlacer questionns

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#551]
method __chip_order
https://github.com/SpiNNakerManchester/PACMAN/blob/4eec6199de9e06c94d8c2cbdad47098402ca9ede/pacman/operations/placer_algorithms/application_placer.py#L365

1. Does the order of Chips matter?
2. What is wrong with the order done by GetMachineProcess
3. Why would  "Mapping", "placer_start_chip" ever be used

Suggestion nuke method and just use Machine,Chips

**Comment by rowleya** [comment]
This is an order that works, but happy to see if using a different order also works...  Worth trying something that consists of a few big app vertices that almost, if not totally, fill a machine.  It might be that the default machine chip order is too random for this to work...

**Comment by Christian-B** [comment]
I am not suggesting a different order.  The question was because the __chip_order method does a lot of work but produces the exact same order as the GetMachineProcess put the Chip into the machine.

Unless "Mapping", "placer_start_chip"  was not 0,0.  Which it appears to always be,

**Comment by rowleya** [comment]
Ah OK, I think this wasn't the case previously which is why the method exists.  Happy for it to be removed in that case though.

**Comment by Christian-B** [comment]
appears yes the order mattered
