### ISSUE TITLE
Routing table minimisation is overly draconian

### ISSUE THREAD

**Issue by mundya** [SpiNNakerManchester/PACMAN#59]
Essentially reported by @SimonDavidson by way of @lplana - routing table minimisation with PACMAN is apparently very slow.  This appears to be a result of driving the minimiser to produce the smallest table possible rather than a table which will fit (see https://github.com/SpiNNakerManchester/PACMAN/blob/master/pacman/operations/router_compressors/mundys_router_compressor/routing_table_condenser.py#L37).  I'd recommend replacing `target_length = None` with `target_length = 1023` or reading the number of free entries from the data reported by the machine.

(Note for the future, a C executable for on-chip minimisation exists but we need to decide what the interface should look like.)

**Comment by rowleya** [comment]
Even better, the surrounding code could simply return the existing table if already under the target length.

**Comment by mundya** [comment]
It's better to set target_length, that way the minimisation will stop once the table is sufficiently small. Returning the table if it's less than the target length will cause any tables which *do* need minimising to be minimised fully rather than only as far as necessary.

**Comment by mundya** [comment]
(Note https://github.com/project-rig/rig/blob/master/rig/routing_table/ordered_covering.py#L266, which is how the minimiser decides whether it needs to do anything)

**Comment by rowleya** [comment]
Because we convert things into a different format, it is probably worth having the if statement on the outside too.  I agree that we should pass a target_length - we did once but seem to have removed it at some point!

**Comment by alan-stokes** [comment]
given the default of the tools is to use the on chip router compressor. Think this issue is no longer important. closing. reopen if beliefs differ.
