### ISSUE TITLE
Routing compression test

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/PACMAN#72]
The current test for routing compression is a bit exact, in that it tests that the result is a specific compression of the table.  Instead, it should go through each entry in the original table and check that following the keys of that entry still results in the same route in the compressed table (noting that the compressed table might be specifically ordered, and so only the first match should be checked).

**Comment by Christian-B** [comment]
Where is the current test?

**Comment by alan-stokes** [comment]
pacman.unittests.operations_tests.router_compessor_tests.test_mundy_compressor.py

**Comment by andrewgait** [comment]
As far as I can see this was dealt with in https://github.com/SpiNNakerManchester/PACMAN/pull/122 and associated PRs, so closing.
